name: Readme Stats

on:
  schedule:
    - cron: '0 */24 * * *'
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Generate README.md
      uses: tarunesh1234/profile-readme-stats-mod@v1.2.0
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        includeForks: true
        includeOrgRepos: true
    # - name: Profile Readme Stats
    #   uses: teoxoy/profile-readme-stats@v2
    #   with:
    #     token: ${{ secrets.ACCESS_TOKEN }}
    #     includeForks: True
    - name: Update README.md
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add .
        git commit -m "Update README"
        git push
        fi
    - name: lastfm to markdown
      uses: melipass/lastfm-to-markdown@v1.3.1
      with:
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          LASTFM_USER: ${{ secrets.LASTFM_USER }}
